apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: achaclinton/jenkins-terraform:my-jenkins-terraform # Replace this with your image name
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      - name: jenkins1
        image: achaclinton/jenkins-terraform:jenkins-terraform
      volumes:
      - name: jenkins-home